app:
  jwt:
    token:
      secret: secret
    expire:
      hours:  24
logging.level:
  com.leapfinance.*: DEBUG
spring:
  application.name: leap-fiance-demo
  jackson.date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
  data:
    redis:
      repositories:
        type: none
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      idle-timeout: 300000
      jdbc-url: jdbc:mysql://localhost:3306/leap?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
      maximum-pool-size: 10
      minimum-idle: 1
      password: mercury
      pool-name: mercury-pool
      username: root
    test-on-borrow: true
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/leap?characterEncoding=UTF-8&autoReconnect=true&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
